tasks:
  cleanup-old-downloads:
    filesystem:
      path: /tmp/downloads
      recursive: true
      mask: "*.part"
    regexp:
      accept:
        - '.+'
    exec:
      command: 'rm -f {location}'
    print:
      format: 'removed: {title}'
