package mvc

import (
	"fmt"
	"path/filepath"
	"strings"
)

// Layout is how the two eyes are arranged in the output frame.
type Layout string

const (
	// LayoutFullSBS keeps both eyes at source width: 3840x1080 from a 1080p
	// disc, so 1920x1080 per eye. This is what a 3D library normally wants —
	// it is the only layout that preserves the disc's resolution.
	LayoutFullSBS Layout = "full"
	// LayoutHalfSBS squeezes both eyes into one source-width frame:
	// 1920x1080 total, so 960x1080 per eye. Half the horizontal detail, and
	// roughly half the bitrate.
	LayoutHalfSBS Layout = "half"
)

// Options configure a conversion.
type Options struct {
	Input   string // .iso, a BDMV directory, or an MKV from MakeMKV
	Output  string // destination .mkv
	TempDir string // scratch space for the demuxed streams
	Layout  Layout
	Encoder Encoder
	// CRF is the quality target for software encoding. Lower is better;
	// 18 is visually transparent for most sources.
	CRF int
	// Preset is x264's speed/efficiency trade-off.
	Preset string
	// VAAPIDevice is the render node for VAAPI encoding.
	VAAPIDevice string
}

// Step is one external command in the conversion.
type Step struct {
	// Name is a short label for progress reporting.
	Name string
	// Argv is the program and its arguments, ready for exec. No shell is
	// involved, so nothing here is quoted or escaped for one.
	Argv []string
	// PipeTo, when set, names the step this one's stdout feeds. The decoder
	// streams raw frames to the encoder rather than writing an intermediate
	// file, which for a feature film is hundreds of gigabytes saved.
	PipeTo string
}

// Plan is the full sequence for one conversion.
type Plan struct {
	Steps []Step
	// Script is the VapourSynth source to write to ScriptPath. It is produced
	// here rather than shipped as a file so the source path, layout and the
	// plugin names stay in one place.
	Script     string
	ScriptPath string
	// Intermediates are the files the steps create, for cleanup.
	Intermediates []string
}

// DefaultOptions returns sensible starting settings. Nothing here varies by
// platform — the encoder is resolved separately, by what is installed.
func DefaultOptions() Options {
	return Options{
		Layout:      LayoutFullSBS,
		Encoder:     EncoderAuto,
		CRF:         18,
		Preset:      "slow",
		VAAPIDevice: "/dev/dri/renderD128",
	}
}

// Validate checks the options are coherent before anything is run. A
// conversion takes hours, so a configuration error must surface immediately
// rather than at the step that trips over it.
func (o Options) Validate(goos string) error {
	if o.Input == "" {
		return fmt.Errorf("no input given")
	}
	if o.Output == "" {
		return fmt.Errorf("no output given")
	}
	if strings.EqualFold(o.Input, o.Output) {
		return fmt.Errorf("input and output are the same file")
	}
	if ext := strings.ToLower(filepath.Ext(o.Output)); ext != ".mkv" {
		return fmt.Errorf("output must be a .mkv (got %q)", ext)
	}
	switch o.Layout {
	case LayoutFullSBS, LayoutHalfSBS:
	default:
		return fmt.Errorf("unknown layout %q (want %q or %q)", o.Layout, LayoutFullSBS, LayoutHalfSBS)
	}
	if !SupportsEncoder(goos, o.Encoder) {
		return fmt.Errorf("encoder %q is not available on %s (have: %s)",
			o.Encoder, goos, encoderList(Encoders(goos)))
	}
	if o.CRF < 0 || o.CRF > 51 {
		return fmt.Errorf("crf %d out of range 0-51", o.CRF)
	}
	return nil
}

func encoderList(encs []Encoder) string {
	s := make([]string, len(encs))
	for i, e := range encs {
		s[i] = string(e)
	}
	return strings.Join(s, ", ")
}

// vapourSynthScript builds the script that decodes both views and stacks them.
//
// mvc-source exposes the base and dependent views as two clips; StackHorizontal
// puts them side by side. For half-SBS each eye is scaled to half width first,
// so the result is one source-width frame rather than two.
func vapourSynthScript(input string, layout Layout) string {
	var b strings.Builder
	b.WriteString("# generated by pipeliner bd3d2sbs — do not edit\n")
	b.WriteString("import vapoursynth as vs\n")
	b.WriteString("core = vs.core\n\n")
	fmt.Fprintf(&b, "base, dependent = core.mvsrc.Source(%s)\n\n", pyQuote(input))
	if layout == LayoutHalfSBS {
		b.WriteString("# Half-SBS: each eye is squeezed to half width so the pair\n")
		b.WriteString("# occupies a single source-width frame.\n")
		b.WriteString("base = core.resize.Spline36(base, width=base.width // 2)\n")
		b.WriteString("dependent = core.resize.Spline36(dependent, width=dependent.width // 2)\n\n")
	}
	b.WriteString("# Left eye first: the near-universal convention for SBS.\n")
	b.WriteString("core.std.StackHorizontal([base, dependent]).set_output()\n")
	return b.String()
}

// pyQuote renders a path as a Python string literal. Windows paths are full of
// backslashes, which Python would read as escapes.
func pyQuote(s string) string {
	return "r'" + strings.ReplaceAll(s, "'", "\\'") + "'"
}

// BuildPlan assembles the conversion for opts. It does not touch the
// filesystem or run anything — the result can be printed for a dry run and is
// what the tests assert against.
func BuildPlan(goos string, opts Options) (*Plan, error) {
	if err := opts.Validate(goos); err != nil {
		return nil, err
	}
	tmp := opts.TempDir
	if tmp == "" {
		tmp = filepath.Dir(opts.Output)
	}
	var (
		meta     = filepath.Join(tmp, "demux.meta")
		script   = filepath.Join(tmp, "stack.vpy")
		videoOut = filepath.Join(tmp, "stacked.264")
	)

	p := &Plan{
		Script:        vapourSynthScript(opts.Input, opts.Layout),
		ScriptPath:    script,
		Intermediates: []string{meta, script, videoOut},
	}

	// 1. Demux. tsMuxeR reads a meta file describing what to extract; writing
	//    it is the runner's job, since it depends on the source's track list.
	p.Steps = append(p.Steps, Step{
		Name: "demux",
		Argv: []string{"tsMuxeR", meta, tmp},
	})

	// 2. Decode both views and stack them, streaming Y4M rather than writing
	//    hundreds of gigabytes of raw frames to disk.
	p.Steps = append(p.Steps, Step{
		Name:   "stack",
		Argv:   []string{"vspipe", "--container", "y4m", script, "-"},
		PipeTo: "encode",
	})

	// 3. Encode.
	p.Steps = append(p.Steps, encodeStep(opts, videoOut))

	// 4. Mux. Audio, subtitle and chapter arguments are appended by the runner
	//    from what the demux actually produced.
	p.Steps = append(p.Steps, Step{
		Name: "mux",
		Argv: []string{"mkvmerge", "-o", opts.Output, videoOut},
	})
	return p, nil
}

// encodeStep builds the encoder invocation. Every variant reads Y4M on stdin,
// which is what lets the decode stream straight into it.
func encodeStep(opts Options, out string) Step {
	switch opts.Encoder {
	case EncoderVAAPI:
		return Step{Name: "encode", Argv: []string{
			"ffmpeg", "-hide_banner", "-y",
			"-vaapi_device", opts.VAAPIDevice,
			"-f", "yuv4mpegpipe", "-i", "-",
			"-vf", "format=nv12,hwupload",
			"-c:v", "h264_vaapi", "-qp", fmt.Sprint(opts.CRF),
			out,
		}}
	case EncoderVideoToolbox:
		return Step{Name: "encode", Argv: []string{
			"ffmpeg", "-hide_banner", "-y",
			"-f", "yuv4mpegpipe", "-i", "-",
			"-c:v", "h264_videotoolbox", "-q:v", fmt.Sprint(opts.CRF),
			out,
		}}
	case EncoderNVENC:
		return Step{Name: "encode", Argv: []string{
			"ffmpeg", "-hide_banner", "-y",
			"-f", "yuv4mpegpipe", "-i", "-",
			"-c:v", "h264_nvenc", "-rc", "constqp", "-qp", fmt.Sprint(opts.CRF),
			out,
		}}
	default:
		return Step{Name: "encode", Argv: []string{
			"x264", "--demuxer", "y4m",
			"--crf", fmt.Sprint(opts.CRF),
			"--preset", opts.Preset,
			"--output", out, "-",
		}}
	}
}

// String renders a plan as the shell-ish transcript a dry run prints. It is
// for reading, not for execution — the steps are run directly, never a shell.
func (p *Plan) String() string {
	var b strings.Builder
	fmt.Fprintf(&b, "# VapourSynth script (%s)\n%s\n", p.ScriptPath, p.Script)
	for i, s := range p.Steps {
		fmt.Fprintf(&b, "# step %d: %s\n", i+1, s.Name)
		b.WriteString(strings.Join(s.Argv, " "))
		if s.PipeTo != "" {
			fmt.Fprintf(&b, "   | (into %q)", s.PipeTo)
		}
		b.WriteString("\n")
	}
	return b.String()
}
